
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpospezyrwvtxuurkreg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwb3NwZXp5cnd2dHh1dXJrcmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjg3MTQsImV4cCI6MjA2MjgwNDcxNH0.8yZm-rnjXHIocVQYxi1JqKTqjmFnTLcv_Q87Fgz10b8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
